### `r .$name`

A total of **`r sum(.$bpn@enrichr@num_sig_up_enrichr, .$bpn@enrichr@num_sig_down_enrichr)`** significantly altered pathways were identified in treatment groups compared to control groups (adjusted p-value <= 0.05) in the Top `r names(.$bpn@enrichr@threshold_up)` and Bottom `r names(.$bpn@enrichr@threshold_down)` of DEGs (**N = `r .$bpn@enrichr@num_upreg` & `r .$bpn@enrichr@num_downreg`, resp.**) by log2FoldChange (**>`r .$bpn@enrichr@threshold_up` or `r .$bpn@enrichr@threshold_down`< **) using **EnrichR**. Of which, we identified **`r .$bpn@enrichr@num_sig_up_enrichr`** up-regulated pathways & **`r .$bpn@enrichr@num_sig_down_enrichr`** down-regulated pathways.

* Number of significantly altered pathways (padj <= 0.05): **`r sum(.$bpn@enrichr@num_sig_up_enrichr, .$bpn@enrichr@num_sig_down_enrichr)`**
* Number of significantly up-regulated pathways: **`r .$bpn@enrichr@num_sig_up_enrichr`**
* Number of significantly down-regulated pathways: **`r .$bpn@enrichr@num_sig_down_enrichr`**

```{r}
format_enrichr_pathways <- function(X) {
  X %>%
    arrange(desc(Combined.Score), Adjusted.P.value) %>%
    select(Term, padj = Adjusted.P.value, CS = Combined.Score, Genes) %>%
    mutate(
      Term = gsub("\\(([^)]+)\\)", "", Term) %>% str_to_sentence,
      padj = round(padj, 3),
      CS = round(CS, 3)
    )
}

make_table(
  .$bpn@enrichr@sig_up_enrichr %>% format_enrichr_pathways,
  caption = paste0(.$name, " Up-Regulated Pathways")
) %>% formatStyle("Term","white-space"="nowrap")
make_table(
  .$bpn@enrichr@sig_down_enrichr %>% format_enrichr_pathways,
  caption = paste0(.$name, " Down-Regulated Pathways")
) %>% formatStyle("Term","white-space"="nowrap")
```