# Enrichr

This is Enrichr.

## Pathways

These are Enrichr pathways.

```{r, results='asis'}
global_state$data %<>%
  map( ~ update_list(., bpn = {system("sleep 3"); quiet(do_enrichr_pod(.$bpn, useFDR=FALSE))}))

global_state$data %>%
  map(~ knit_child(
    "Rmd/enrichr_pathways.Rmd",
    envir = environment(),
    quiet = TRUE
  )) %>%
  list_c() %>%
  cat(sep = "\n")
```

## PAVER

These are PAVER plots of the pathways from all comparisons

```{r, results='asis'}
input = global_state$data %>%
  map(~ bind_rows(.$bpn@enrichr@sig_up_enrichr, .$bpn@enrichr@sig_down_enrichr %>% mutate(Combined.Score = Combined.Score * -1))) %>%
  bind_rows(.id = "Group") %>%
  select(GOID = Term, CS = Combined.Score, Group) %>%
  mutate(CS = sign(CS) * log2(abs(CS)) + 1) %>%
  mutate(GOID = str_extract(GOID, "\\bGO:\\d+")) %>%
  distinct(GOID, Group, .keep_all = T) %>%
  pivot_wider(names_from = Group, values_from = CS)

minClusterSize = 5
maxCoreScatter = 0.33
minGap = (1 - maxCoreScatter) * 3 / 4

ENRICHR_PAVER_result <- quiet(PAVER::prepare_data(input, global_state$embeddings, global_state$term2name) %>%
  PAVER::generate_themes(maxCoreScatter = maxCoreScatter,
  minGap = minGap,
  minClusterSize = minClusterSize))

global_state$results <- c(global_state$results, lst(ENRICHR_PAVER_result))

list(ENRICHR_PAVER_result, "logCS") %>%
  knit_child(text = readLines("Rmd/paver_report.Rmd"),
             envir = environment(),
             quiet = TRUE) %>%
  cat(sep = "\n")
```
